### ISSUE TITLE
一些语意问题

### ISSUE THREAD

**Issue by hahaDong** [Joker-lkc/sweetalk-data-structure#33]
1. 《2.5算法效率度量的方法》

 - ”和编程语言有关，越高级的语言执行效率月底“：错别字，建议修改为”...执行效率越低“
 - “有些算法时不能事后再统计的，如：导弹控制算法”：错别字，建议修改为“有些算法是...”
 - 图名为「不同算法的操作数量对比」上方 “最重要的是把程序看成时...”：错别字，建议修改为“...把程序看成是”

2. 《2.7 算法空间复杂度》
- “算法所需存储空间的多少也是衡量其新跟那个的一个重要方面”：错别字，建议修改为“...也是衡量其新性能一个重要方面”
- “空间换时间算法”思路：“index 的下标对应无序数组中的数字，对应下标存储的数，对应下标出现的次数，”不明晰

**Comment by Joker-lkc** [comment]
收到反馈，感谢建议，已修改。
